export const ResourceKind = Object.freeze({ Wood:'wood', Stone:'stone', Metal:'metal', Fuel:'fuel' });
export const AutoActionKind = Object.freeze({ None:'none', Enemy:'enemy', FurnaceRepair:'furnace-repair', FurnaceDeposit:'furnace-deposit', Rescue:'rescue', Barricade:'barricade', Resource:'resource' });
const EPS=1e-6;
export const vec3=v=>({x:v[0],y:v[1],z:v[2]});
export const distance2D=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
export const clampPosition=(p,c)=>({x:Math.max(-c.world.boundX,Math.min(c.world.boundX,p.x)),y:p.y,z:Math.max(-c.world.boundZ,Math.min(c.world.boundZ,p.z))});
export function companionIdsFor(lead){if(lead==='Character1')return['Character2','Character3','Character4'];if(lead==='Character2')return['Character1','Character3','Character4'];throw new Error(`Invalid starting lead: ${lead}`);}
export function gatherSecondsFor(c,k){const v=c.openingLoopTuning?.gatherSecondsPerUnit?.[k];if(!Number.isFinite(v)||v<=0)throw new Error(`No valid gather timing for ${k}`);return v;}

export class Inventory{
  constructor(capacity=0){this.capacity=capacity>0?capacity:0;this.items=[];}
  get count(){return this.items.length;} get full(){return this.capacity>0&&this.count>=this.capacity;} get empty(){return this.count===0;}
  countKind(k){return this.items.filter(x=>x===k).length;}
  add(k){if(this.full)return false;this.items.push(k);return true;}
  removeFirst(k=null){if(this.empty)return null;if(k==null)return this.items.shift()??null;const i=this.items.indexOf(k);return i<0?null:(this.items.splice(i,1)[0]??null);}
  clear(){const x=[...this.items];this.items.length=0;return x;}
}

class ResourceNodeState{
  constructor(id,kind,position,units,secondsPerUnit){Object.assign(this,{id,kind,position,unitsRemaining:units,secondsPerUnit,progressSeconds:0});}
  get depleted(){return this.unitsRemaining<=0;}
  stepGather(dt,inventory){if(this.depleted||inventory.full)return 0;this.progressSeconds+=Math.max(0,dt);let n=0;while(this.progressSeconds+EPS>=this.secondsPerUnit&&!this.depleted&&!inventory.full){this.progressSeconds-=this.secondsPerUnit;if(!inventory.add(this.kind))break;this.unitsRemaining--;n++;}return n;}
}
class FurnaceState{
  constructor(c){this.contract=c;this.maxDurability=c.openingLoopTuning.furnaceMaxDurability;this.durability=this.maxDurability;this.stored={wood:0,stone:0,metal:0,fuel:0};this.level=1;this.depositProgressSeconds=0;this.repairProgressSeconds=0;}
  get operational(){return this.durability>0;} get warmthRadius(){const t=this.contract.openingLoopTuning;return t.warmthRadiusLevel1+(this.level-1)*t.warmthRadiusPerAdditionalLevel;}
  recomputeLevel(){const t=this.contract.openingLoopTuning;let n=1;if(meets(this.stored,t.furnaceLevel2))n=2;if(meets(this.stored,t.furnaceLevel3))n=3;if(meets(this.stored,t.furnaceLevel4))n=4;const changed=n!==this.level;this.level=n;return changed;}
  stepDeposit(dt,inv){if(inv.empty||!this.operational)return{deposited:null,levelChanged:false};this.depositProgressSeconds+=Math.max(0,dt);const s=this.contract.openingLoopTuning.furnaceDepositSecondsPerUnit;if(this.depositProgressSeconds+EPS<s)return{deposited:null,levelChanged:false};this.depositProgressSeconds=0;const item=inv.removeFirst();if(item==null)return{deposited:null,levelChanged:false};this.stored[item]=(this.stored[item]??0)+1;return{deposited:item,levelChanged:this.recomputeLevel()};}
  stepRepair(dt,inv){const t=this.contract.openingLoopTuning;if(this.durability>=this.maxDurability||inv.countKind(ResourceKind.Wood)<=0)return false;this.repairProgressSeconds+=Math.max(0,dt);if(this.repairProgressSeconds+EPS<t.furnaceRepairSecondsPerUnit)return false;this.repairProgressSeconds=0;if(inv.removeFirst(ResourceKind.Wood)==null)return false;this.durability=Math.min(this.maxDurability,this.durability+t.furnaceRepairPerWood);return true;}
}
class ConstructionSiteState{
  constructor(id,position,req,seconds){this.id=id;this.position=position;this.requirement={wood:req.wood??0,stone:req.stone??0,metal:req.metal??0};this.delivered={wood:0,stone:0,metal:0};this.secondsPerUnit=seconds;this.progressSeconds=0;this.built=false;this.health=0;this.maxHealth=160;}
  get progress(){const r=this.requirement.wood+this.requirement.stone+this.requirement.metal,d=this.delivered.wood+this.delivered.stone+this.delivered.metal;return r<=0?1:Math.min(1,d/r);}
  canAccept(k){return!this.built&&(this.delivered[k]??0)<(this.requirement[k]??0);}
  deliverOne(inv){for(const k of [ResourceKind.Wood,ResourceKind.Stone,ResourceKind.Metal]){if(!this.canAccept(k)||inv.removeFirst(k)==null)continue;this.delivered[k]++;if(meets(this.delivered,this.requirement)){this.built=true;this.health=this.maxHealth;}return k;}return null;}
  stepContribute(dt,inv){if(this.built||!canSiteAcceptInventory(this,inv))return null;this.progressSeconds+=Math.max(0,dt);if(this.progressSeconds+EPS<this.secondsPerUnit)return null;this.progressSeconds=0;return this.deliverOne(inv);}
}
export function meets(h,r){return!!r&&(h.wood??0)>=(r.wood??0)&&(h.stone??0)>=(r.stone??0)&&(h.metal??0)>=(r.metal??0)&&(h.fuel??0)>=(r.fuel??0);}

export function createInitialState(c,selectedLead='Character1'){
  const failures=validateContract(c);if(failures.length)throw new Error(failures.join(' | '));
  const inv=new Inventory(c.player.carryCapacity);
  const resources=[];
  c.world.woodNodes.forEach((p,i)=>resources.push(new ResourceNodeState(`wood-${i+1}`,ResourceKind.Wood,vec3(p),c.openingLoopTuning.woodUnitsPerNode,gatherSecondsFor(c,ResourceKind.Wood))));
  c.world.stoneNodes.forEach((p,i)=>resources.push(new ResourceNodeState(`stone-${i+1}`,ResourceKind.Stone,vec3(p),c.openingLoopTuning.stoneUnitsPerNode,gatherSecondsFor(c,ResourceKind.Stone))));
  resources.push(new ResourceNodeState('metal-1',ResourceKind.Metal,vec3(c.world.metalNode),c.openingLoopTuning.metalUnitsPerNode,gatherSecondsFor(c,ResourceKind.Metal)));
  resources.push(new ResourceNodeState('fuel-1',ResourceKind.Fuel,vec3(c.world.fuelNode),c.openingLoopTuning.fuelUnitsPerNode,gatherSecondsFor(c,ResourceKind.Fuel)));
  return{contract:c,selectedLead,companions:companionIdsFor(selectedLead),player:{position:vec3(c.player.spawn),velocity:{x:0,y:0,z:0},facing:{x:0,z:-1},sprinting:false,health:100},inventory:inv,resources,furnace:new FurnaceState(c),survivor:{position:vec3(c.world.survivor),rescued:false,rescueProgressSeconds:0},defenses:{north:new ConstructionSiteState('north',vec3(c.world.northBarricade),c.openingLoopTuning.northBarricadeBuild,c.openingLoopTuning.playerConstructionSecondsPerUnit),south:new ConstructionSiteState('south',vec3(c.world.southBarricade),c.openingLoopTuning.southBarricadeBuild,c.openingLoopTuning.playerConstructionSecondsPerUnit)},waves:{unlocked:false,active:false,waveNumber:0,completedWaves:0,timer:c.openingLoopTuning.firstWaveDelaySeconds,enemies:[]},helper:{active:false,state:'trapped',position:vec3(c.world.survivor)},action:{kind:AutoActionKind.None,id:null,progress:0,label:'None'},elapsedSeconds:0};
}

export function movePlayer(s,input,dt){const c=s.contract,x=Math.max(-1,Math.min(1,input.x??0)),z=Math.max(-1,Math.min(1,input.z??0)),m=Math.hypot(x,z),n=m>1?{x:x/m,z:z/m}:{x,z},moving=Math.hypot(n.x,n.z)>.001,spd=input.sprint?c.player.runSpeed:c.player.walkSpeed,t={x:n.x*spd,z:n.z*spd},rate=moving?c.player.acceleration:c.player.deceleration;s.player.velocity.x=moveToward(s.player.velocity.x,t.x,rate*dt);s.player.velocity.z=moveToward(s.player.velocity.z,t.z,rate*dt);s.player.position=clampPosition({x:s.player.position.x+s.player.velocity.x*dt,y:s.player.position.y,z:s.player.position.z+s.player.velocity.z*dt},c);if(moving){const l=Math.hypot(n.x,n.z)||1;s.player.facing={x:n.x/l,z:n.z/l};}s.player.sprinting=!!input.sprint;return moving;}
const moveToward=(a,b,d)=>Math.abs(b-a)<=d?b:a+Math.sign(b-a)*d;
const priority=(c,k)=>({[AutoActionKind.Enemy]:c.openingLoopTuning.automaticActionPriorities.enemy,[AutoActionKind.FurnaceRepair]:c.openingLoopTuning.automaticActionPriorities.furnaceRepair,[AutoActionKind.Rescue]:c.openingLoopTuning.automaticActionPriorities.rescue,[AutoActionKind.FurnaceDeposit]:c.openingLoopTuning.automaticActionPriorities.furnaceDeposit,[AutoActionKind.Barricade]:c.openingLoopTuning.automaticActionPriorities.construction,[AutoActionKind.Resource]:c.openingLoopTuning.automaticActionPriorities.resource}[k]??0);
function addCandidate(s,out,kind,id,pos,radius,label,hyst=false){const d=distance2D(s.player.position,pos),range=radius+(hyst?s.contract.openingLoopTuning.automaticActionTargetHysteresis:0);if(d>range)return null;const dx=pos.x-s.player.position.x,dz=pos.z-s.player.position.z,l=Math.hypot(dx,dz),dir=l>.001?{x:dx/l,z:dz/l}:s.player.facing,dot=Math.max(-1,Math.min(1,dir.x*s.player.facing.x+dir.z*s.player.facing.z)),face=(dot+1)*.5,ds=1-Math.max(0,Math.min(1,d/Math.max(.01,radius))),t=s.contract.openingLoopTuning,c={kind,id,position:pos,radius,distance:d,score:priority(s.contract,kind)+ds*t.automaticActionDistanceScoreWeight+face*t.automaticActionFacingWeight,label,progress:0};out?.push(c);return c;}
const canSiteAcceptInventory=(site,inv)=>[ResourceKind.Wood,ResourceKind.Stone,ResourceKind.Metal].some(k=>site.canAccept(k)&&inv.countKind(k)>0);
export function actionCandidates(s){const out=[],c=s.contract;for(const e of s.waves.enemies)if(e.alive)addCandidate(s,out,AutoActionKind.Enemy,e.id,e.position,c.player.combatRadius,'Fight wolf');const f=vec3(c.world.furnace);if(s.furnace.durability<s.furnace.maxDurability&&s.inventory.countKind(ResourceKind.Wood)>0)addCandidate(s,out,AutoActionKind.FurnaceRepair,'furnace',f,c.player.depositRadius,'Repair furnace');else if(!s.inventory.empty&&s.furnace.operational)addCandidate(s,out,AutoActionKind.FurnaceDeposit,'furnace',f,c.player.depositRadius,'Feed furnace');if(!s.survivor.rescued&&s.furnace.operational&&s.furnace.level>=2)addCandidate(s,out,AutoActionKind.Rescue,'survivor',s.survivor.position,c.player.rescueRadius,'Rescue survivor');for(const site of [s.defenses.north,s.defenses.south])if(!site.built&&canSiteAcceptInventory(site,s.inventory))addCandidate(s,out,AutoActionKind.Barricade,site.id,site.position,c.player.buildRadius,`Build ${site.id} barricade`);for(const n of s.resources)if(!n.depleted)addCandidate(s,out,AutoActionKind.Resource,n.id,n.position,c.player.interactionRadius,`Gather ${n.kind}`);return out.sort((a,b)=>b.score-a.score||a.distance-b.distance||a.id.localeCompare(b.id));}
function retained(s,p){if(!p?.id||p.kind===AutoActionKind.None)return null;const c=s.contract;if(p.kind===AutoActionKind.Enemy){const e=s.waves.enemies.find(x=>x.id===p.id&&x.alive);return e&&addCandidate(s,null,p.kind,p.id,e.position,c.player.combatRadius,p.label||'Fight wolf',true);}if(p.kind===AutoActionKind.FurnaceRepair&&s.furnace.durability<s.furnace.maxDurability&&s.inventory.countKind(ResourceKind.Wood)>0)return addCandidate(s,null,p.kind,'furnace',vec3(c.world.furnace),c.player.depositRadius,p.label||'Repair furnace',true);if(p.kind===AutoActionKind.FurnaceDeposit&&!s.inventory.empty&&s.furnace.operational&&s.furnace.durability>=s.furnace.maxDurability)return addCandidate(s,null,p.kind,'furnace',vec3(c.world.furnace),c.player.depositRadius,p.label||'Feed furnace',true);if(p.kind===AutoActionKind.Rescue&&!s.survivor.rescued)return addCandidate(s,null,p.kind,'survivor',s.survivor.position,c.player.rescueRadius,p.label||'Rescue survivor',true);if(p.kind===AutoActionKind.Barricade){const site=s.defenses[p.id];return site&&!site.built&&canSiteAcceptInventory(site,s.inventory)&&addCandidate(s,null,p.kind,p.id,site.position,c.player.buildRadius,p.label,true);}if(p.kind===AutoActionKind.Resource){const n=s.resources.find(x=>x.id===p.id);return n&&!n.depleted&&addCandidate(s,null,p.kind,p.id,n.position,c.player.interactionRadius,p.label,true);}return null;}
export function chooseAutoAction(s,p=s.action){const r=retained(s,p);if(r)return{...r,progress:p.progress??0};const c=actionCandidates(s);return c[0]??{kind:AutoActionKind.None,id:null,label:'None',progress:0};}
export function stepAutoAction(s,dt){const a=s.action,t=s.contract.openingLoopTuning;if(!a||a.kind===AutoActionKind.None)return null;if(a.kind===AutoActionKind.Resource){const n=s.resources.find(x=>x.id===a.id);if(!n)return null;const g=n.stepGather(dt,s.inventory);a.progress=Math.min(1,n.progressSeconds/n.secondsPerUnit);return g?{type:'gather',kind:n.kind,amount:g}:null;}if(a.kind===AutoActionKind.FurnaceDeposit){const r=s.furnace.stepDeposit(dt,s.inventory);a.progress=Math.min(1,s.furnace.depositProgressSeconds/t.furnaceDepositSecondsPerUnit);return r.deposited?{type:'deposit',kind:r.deposited,levelChanged:r.levelChanged,level:s.furnace.level}:null;}if(a.kind===AutoActionKind.FurnaceRepair){const r=s.furnace.stepRepair(dt,s.inventory);a.progress=Math.min(1,s.furnace.repairProgressSeconds/t.furnaceRepairSecondsPerUnit);return r?{type:'furnace-repair',durability:s.furnace.durability}:null;}if(a.kind===AutoActionKind.Rescue){s.survivor.rescueProgressSeconds+=Math.max(0,dt);a.progress=Math.min(1,s.survivor.rescueProgressSeconds/t.survivorRescueSeconds);if(s.survivor.rescueProgressSeconds+EPS>=t.survivorRescueSeconds){s.survivor.rescued=true;s.helper.active=true;s.helper.state='following';return{type:'rescue'};}return null;}if(a.kind===AutoActionKind.Barricade){const site=s.defenses[a.id],k=site?.stepContribute(dt,s.inventory);if(!site)return null;a.progress=site.progress;return k?{type:'build',site:a.id,kind:k,built:site.built,progress:site.progress}:null;}if(a.kind===AutoActionKind.Enemy){const e=s.waves.enemies.find(x=>x.id===a.id&&x.alive);if(!e)return null;e.hitCooldown=(e.hitCooldown??0)-dt;if(e.hitCooldown>0)return null;e.hitCooldown=t.wolf.playerHitSeconds;e.health-=t.wolf.playerDamagePerHit;if(e.health<=0)e.alive=false;return{type:'enemy-hit',id:e.id,alive:e.alive,health:Math.max(0,e.health)};}return null;}
export function updateWaveGate(s,dt){const t=s.contract.openingLoopTuning;s.waves.unlocked=s.furnace.level>=2&&s.survivor.rescued&&s.defenses.north.built;if(!s.waves.unlocked||s.waves.active)return null;s.waves.timer=Math.max(0,s.waves.timer-dt);if(s.waves.timer>0)return null;s.waves.waveNumber++;s.waves.active=true;const count=2+s.waves.waveNumber;s.waves.enemies=Array.from({length:count},(_,i)=>({id:`wave-${s.waves.waveNumber}-wolf-${i+1}`,health:t.wolf.health,alive:true,position:{x:(i-(count-1)*.5)*1.8,y:0,z:i%2===0?-t.wolf.spawnZ:t.wolf.spawnZ},hitCooldown:0,attackCooldown:0}));return{type:'wave-start',wave:s.waves.waveNumber,count};}
export function completeWaveIfClear(s){if(!s.waves.active||s.waves.enemies.some(e=>e.alive))return false;s.waves.active=false;s.waves.completedWaves++;const t=s.contract.openingLoopTuning;s.waves.timer=Math.max(t.minimumWaveDelaySeconds,t.firstWaveDelaySeconds-s.waves.completedWaves*t.waveDelayReductionPerCompletedWave);return true;}

export function validateContract(c){const f=[];if(!c||typeof c!=='object')return['Contract is missing or invalid.'];if(c.contractVersion!=='1.3.1')f.push(`Expected contractVersion 1.3.1; got ${c.contractVersion}.`);if(c.product!=='HAVENLINE')f.push('Contract product must be HAVENLINE.');if(c.camera?.projection!=='orthographic')f.push('Shipping camera must remain orthographic.');if(c.player?.unlimitedCarry!==true)f.push('Carrying must be explicitly unlimited.');if(c.player?.carryCapacity!==0)f.push('Unlimited carrying must use carryCapacity 0.');if(!Number.isInteger(c.player?.visibleCarrySlots)||c.player.visibleCarrySlots<24)f.push('Visible carry stack budget is too small.');if(c.characterSystem?.activeCrewSize!==4)f.push('Active core crew size must be 4.');if((c.openingLoopTuning?.furnaceLevel2?.wood??0)!==18||(c.openingLoopTuning?.furnaceLevel2?.stone??0)!==6)f.push('Furnace L2 must require 18 wood + 6 stone.');if(c.openingLoopTuning?.firstWaveEnemyCount!==3)f.push('First wave must contain three wolves.');for(const k of Object.values(ResourceKind))try{gatherSecondsFor(c,k);}catch(e){f.push(e.message);}return f;}
export function runDeterministicContractQA(c){const checks=[],push=(id,pass,details)=>checks.push({id,pass:!!pass,details});const failures=validateContract(c);push('contract-shape',!failures.length,failures.length?failures.join(' | '):'Uncapped reference-game carrying is locked.');if(failures.length)return{passed:false,checks};push('crew-c1',JSON.stringify(companionIdsFor('Character1'))===JSON.stringify(['Character2','Character3','Character4']),'C1 produces C2/C3/C4 companions.');const inv=new Inventory(c.player.carryCapacity);for(let i=0;i<128;i++)inv.add(ResourceKind.Wood);push('uncapped-carry',inv.count===128&&!inv.full,`Inventory accepted ${inv.count} items with no cap.`);const state=createInitialState(c,'Character1'),wood=state.resources.find(n=>n.kind===ResourceKind.Wood);for(let i=0;i<64;i++)state.inventory.add(ResourceKind.Stone);const before=state.inventory.count;wood.stepGather(wood.secondsPerUnit+.01,state.inventory);push('gather-over-old-cap',state.inventory.count>before,`Gathering continued at load ${before}+.`);state.furnace.stored.wood=18;state.furnace.stored.stone=6;state.furnace.recomputeLevel();push('furnace-level2',state.furnace.level===2,`Furnace level ${state.furnace.level}.`);state.survivor.rescued=true;state.inventory.items.push(...Array(8).fill(ResourceKind.Wood));for(let i=0;i<8;i++)state.defenses.north.deliverOne(state.inventory);state.inventory.items.push(...Array(3).fill(ResourceKind.Stone));for(let i=0;i<3;i++)state.defenses.north.deliverOne(state.inventory);state.waves.timer=0;const w=updateWaveGate(state,.1);push('first-wave-gate',w?.count===3,'First unlocked wave spawned three wolves.');return{passed:checks.every(x=>x.pass),checks};}
